USE [dbTeste]
GO
/****** Object:  Table [dbo].[tb01]    Script Date: 06/08/2018 16:41:28 ******/
DROP TABLE [dbo].[tb01]
GO
USE [master]
GO
/****** Object:  Database [dbTeste]    Script Date: 06/08/2018 16:41:28 ******/
DROP DATABASE [dbTeste]
GO
/****** Object:  Database [dbTeste]    Script Date: 06/08/2018 16:41:28 ******/
CREATE DATABASE [dbTeste] ON  PRIMARY 
( NAME = N'dbTeste', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\dbTeste.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbTeste_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\dbTeste_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbTeste].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbTeste] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbTeste] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbTeste] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbTeste] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbTeste] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbTeste] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbTeste] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbTeste] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbTeste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbTeste] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbTeste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbTeste] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbTeste] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbTeste] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbTeste] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dbTeste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbTeste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbTeste] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbTeste] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbTeste] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbTeste] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbTeste] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbTeste] SET RECOVERY FULL 
GO
ALTER DATABASE [dbTeste] SET  MULTI_USER 
GO
ALTER DATABASE [dbTeste] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbTeste] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbTeste', N'ON'
GO
USE [dbTeste]
GO
/****** Object:  Table [dbo].[tb01]    Script Date: 06/08/2018 16:41:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tb01](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](10) NOT NULL,
 CONSTRAINT [PK_tb01] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[tb01] ON 

INSERT [dbo].[tb01] ([Id], [Nome]) VALUES (1, N'Nome 1')
INSERT [dbo].[tb01] ([Id], [Nome]) VALUES (2, N'Nome 2')
INSERT [dbo].[tb01] ([Id], [Nome]) VALUES (3, N'Nome 3')
INSERT [dbo].[tb01] ([Id], [Nome]) VALUES (4, N'Nome 4')
INSERT [dbo].[tb01] ([Id], [Nome]) VALUES (10, N'123456')
SET IDENTITY_INSERT [dbo].[tb01] OFF
USE [master]
GO
ALTER DATABASE [dbTeste] SET  READ_WRITE 
GO
