


USE [dbProceduresFunctionsViews]
GO


-- APAGUE PRIMEIRO AS TABELAS FILHAS
IF OBJECT_ID('tbPedido', 'U') IS NOT NULL
DROP TABLE tbPedido;
GO

-- DEPOIS DE APAGAR AS TABELAS FILHAS APAGUE AS MAES
IF OBJECT_ID('tbProduto', 'U') IS NOT NULL
DROP TABLE tbProduto;
GO



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbProduto](
	[CodProduto] [int] IDENTITY(1,1) NOT NULL,
	[NomeProduto] [varchar](200) NOT NULL,
	[Preco] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_tbProduto] PRIMARY KEY CLUSTERED 
(
	[CodProduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbPedido](
	[CodPedido] [int] NOT NULL,
	[CodProduto] [int] NOT NULL,
	[Quantidade] [int] NOT NULL,
 CONSTRAINT [PK_tbPedido] PRIMARY KEY CLUSTERED 
(
	[CodPedido] ASC,
	[CodProduto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

